name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build with Buildozer Action
        uses: ArtemSydoryk/buildozer-action@v1
        with:
          save_artifact: true
          artifact_name: SiparisTakip-APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SiparisTakip-APK
          path: bin/*.apk
