name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: flet-dev/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug
          subfolder: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SiparisTakip-APK
          path: bin/*.apk
